<!--
Copyright © SMM > for MMS, Inc. All rights reserved.
-->

<script>
    var scene = new THREE.Scene();
    var clock = new THREE.Clock();
    var camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 300);
    camera.position.set(2, 5, 3);

    var renderer = new THREE.WebGLRenderer({
        antialias: true
    });
    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);

    var controls = new THREE.OrbitControls(camera, renderer.domElement);

    var group = new THREE.Group();
    group.scale.set(3, .5, 2);
    scene.add(group)

    setPlane("y",  Math.PI * 0.5, 0xEAEAEA); //px
    setPlane("y", -Math.PI * 0.5, 0xEAEAEA); //nx
    setPlane("x",  Math.PI * 0.5, 0xAAAAAA); //ny
    setPlane("y",  0, 0xAEAEAE); //pz
    setPlane("y",  Math.PI, 0xAEAEAE);// nz
    setPlane("x",  -Math.PI * 0.5, 0xAAAAAA); //ny

    function setPlane(axis, angle, color) {
        let planeGeom = new THREE.PlaneGeometry(1, 1, 1, 1);
        planeGeom.translate(0, 0, 0.5);
        switch (axis) {
            case 'y':
                planeGeom.rotateY(angle);
                break;
            default:
                planeGeom.rotateX(angle);
        }
        let plane = new THREE.Mesh(planeGeom, new THREE.MeshBasicMaterial({color: color, side: THREE.DoubleSide}));
        group.add(plane);
    }

    var gui = new dat.GUI();
    gui.add(group.scale, "x", 0.1, 5);
    gui.add(group.scale, "y", 0.1, 5);
    gui.add(group.scale, "z", 0.1, 5);

    function render() {

        requestAnimationFrame(render);
        renderer.render(scene, camera);
    }

    render();

</script>

<?php $product = $block->getProduct(); ?>